; This file for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_untitled=music_data_untitled
.endif

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4
	.byte .lobyte(@tempo_env_10_mid), .hibyte(@tempo_env_10_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:

@samples:
@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $00,$c0,$7f,$00,$01
@env2:
	.byte $7f,$00,$00
@tempo_env_10_mid:
	.byte $03,$04,$06,$05,$05,$05,$80
@song0ch0:
@song0ch0loop:
	.byte $6a, .lobyte(@tempo_env_10_mid), .hibyte(@tempo_env_10_mid)
@song0ref5:
	.byte $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b
	.byte $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b
	.byte $ff, $18
	.word @song0ref5
	.byte $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref44:
	.byte $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf
	.byte $ff, $18
	.word @song0ref44
	.byte $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $ff, $18
	.word @song0ref44
	.byte $ff, $18
	.word @song0ref44
	.byte $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $ff, $18
	.word @song0ref44
	.byte $ff, $18
	.word @song0ref44
	.byte $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $18
	.word @song0ref44
	.byte $ff, $18
	.word @song0ref44
	.byte $fd
	.word @song0ch4loop
